let ctx=null,currentPage='dashboard';const C=document.getElementById('leaderContent');document.getElementById('logoutBtn').onclick=signOutB13;document.querySelectorAll('#leaderNav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
(async()=>{ctx=await getSessionProfile();if(!ctx)return;await b13LoadSettings();if(!['gerente','sub_lider','lider'].includes(ctx.profile.role)){location.href='member.html';return;}document.getElementById('userName').textContent=ctx.profile.name;document.getElementById('userRole').textContent=ctx.profile.role.replace('_',' ').toUpperCase();go('dashboard');})();
function go(p){currentPage=p;document.querySelectorAll('#leaderNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render();}window.go=go;
function header(t,s){document.getElementById('pageTitle').textContent=t;document.getElementById('pageSubtitle').textContent=s||'';}
async function profiles(){return await b13Rpc('b13_admin_profiles',{p_token:b13Token()})||[];}
async function deliveries(){return await b13Rpc('b13_admin_deliveries',{p_token:b13Token()})||[];}
async function render(){C.innerHTML='<div class="loading">Carregando administração...</div>';try{if(currentPage==='dashboard')await dashboard();if(currentPage==='members')await members();if(currentPage==='approvals')await approvals();if(currentPage==='deliveries')await allDeliveries();if(currentPage==='payments')await payments();if(currentPage==='goals')await goals();if(currentPage==='ranking')await ranking();if(currentPage==='notices')await notices();if(currentPage==='logs')await logs();if(currentPage==='settings')await settings();}catch(e){C.innerHTML=`<div class="error-card">${(e.message||e).replace('B13: ','')}</div>`}}
async function dashboard(){header('Dashboard','Visão geral da organização');const ps=await profiles(),ds=await deliveries(),active=ps.filter(p=>p.approved&&p.status==='ativo').length,pendingMembers=ps.filter(p=>!p.approved).length,pending=ds.filter(d=>d.payment_status==='pendente').reduce((s,d)=>s+Number(d.member_amount),0),leaves=ds.reduce((s,d)=>s+Number(d.leaves),0);C.innerHTML=`<div class="admin-metrics"><div><span>MEMBROS ATIVOS</span><strong>${active}</strong><small>${pendingMembers} aguardando aprovação</small></div><div><span>PAGAMENTOS PENDENTES</span><strong>${money(pending)}</strong><small>valor para membros</small></div><div><span>FOLHAS REGISTRADAS</span><strong>${leaves.toLocaleString('pt-BR')}</strong><small>${(leaves*B13_RULES.kitsPerLeaf).toLocaleString('pt-BR')} kits</small></div><div><span>ENTREGAS</span><strong>${ds.length}</strong><small>registros totais</small></div></div><div class="leader-grid"><section class="admin-block"><div class="admin-block-head"><h3>Pagamentos aguardando</h3><button onclick="go('payments')">ABRIR CENTRAL</button></div>${paymentMini(ds.filter(d=>d.payment_status==='pendente').slice(0,6))}</section><section class="admin-block"><div class="admin-block-head"><h3>Novos cadastros</h3><button onclick="go('approvals')">VER TODOS</button></div><div class="admin-list">${ps.filter(p=>!p.approved).slice(0,6).map(p=>`<div><span><b>${p.name}</b><small>ID ${p.rp_id}</small></span><em>PENDENTE</em></div>`).join('')||'<p class="muted">Nenhum cadastro pendente.</p>'}</div></section></div>`;}
function paymentMini(ds){return `<div class="admin-list">${ds.map(d=>`<div><span><b>${d.member_name||'Membro'}</b><small>${d.leaves} folhas • ${new Date(d.created_at).toLocaleDateString('pt-BR')}</small></span><strong>${money(d.member_amount)}</strong></div>`).join('')||'<p class="muted">Nenhum pagamento pendente.</p>'}</div>`;}
async function members(){header('Membros','Gerencie cargos e acessos');const ps=(await profiles()).filter(p=>p.approved);C.innerHTML=`<div class="admin-block"><div class="admin-block-head"><h3>Membros cadastrados</h3><span>${ps.length} registros</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Nome</th><th>ID</th><th>Discord</th><th>Cargo</th><th>Status</th><th>Ações</th></tr></thead><tbody>${ps.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.rp_id}</td><td>${p.discord||'-'}</td><td><select onchange="changeRole('${p.id}',this.value)">${['membro','recrutador','gerente','sub_lider','lider'].map(r=>`<option value="${r}" ${p.role===r?'selected':''}>${r.replace('_',' ')}</option>`).join('')}</select></td><td><span class="status ${p.status==='ativo'?'pago':'pendente'}">${p.status}</span></td><td><button class="small-action" onclick="toggleStatus('${p.id}','${p.status}')">${p.status==='ativo'?'Desativar':'Ativar'}</button></td></tr>`).join('')}</tbody></table></div></div>`;}
window.changeRole=async(id,role)=>{try{await b13Rpc('b13_admin_set_role',{p_token:b13Token(),p_account_id:id,p_role:role});showToast('Cargo atualizado.');}catch(e){showToast((e.message||e).replace('B13: ',''),'error')}};
window.toggleStatus=async(id,status)=>{try{await b13Rpc('b13_admin_set_status',{p_token:b13Token(),p_account_id:id,p_status:status==='ativo'?'inativo':'ativo'});showToast('Status atualizado.');members();}catch(e){showToast((e.message||e).replace('B13: ',''),'error')}};
async function approvals(){header('Aprovações','Novos membros aguardando acesso');const ps=(await profiles()).filter(p=>!p.approved);C.innerHTML=`<div class="approval-grid">${ps.map(p=>`<article class="approval-card"><div class="approval-id">ID ${p.rp_id}</div><h3>${p.name}</h3><p>${p.discord||'Sem Discord informado'}</p><small>${new Date(p.created_at).toLocaleString('pt-BR')}</small><div><button class="approve" onclick="approveMember('${p.id}')">APROVAR</button><button class="reject" onclick="rejectMember('${p.id}')">RECUSAR</button></div></article>`).join('')||'<div class="empty-admin">Nenhum cadastro aguardando aprovação.</div>'}</div>`;}
window.approveMember=async id=>{try{await b13Rpc('b13_admin_approve',{p_token:b13Token(),p_account_id:id,p_approved:true});showToast('Membro aprovado.');approvals();}catch(e){showToast((e.message||e).replace('B13: ',''),'error')}};
window.rejectMember=async id=>{try{await b13Rpc('b13_admin_approve',{p_token:b13Token(),p_account_id:id,p_approved:false});showToast('Cadastro recusado.');approvals();}catch(e){showToast((e.message||e).replace('B13: ',''),'error')}};
async function allDeliveries(){header('Entregas','Todas as entregas registradas');const ds=await deliveries();C.innerHTML=`<div class="admin-block"><div class="admin-block-head"><h3>Histórico geral</h3><span>${ds.length} entregas</span></div>${deliveryTable(ds)}</div>`;}
function deliveryTable(ds,actions=false){return `<div class="table-wrap"><table class="admin-table"><thead><tr><th>Membro</th><th>Data</th><th>Folhas</th><th>Kits</th><th>Total</th><th>Membro ${Math.round(B13_RULES.memberPercent*100)}%</th><th>Status</th>${actions?'<th>Ação</th>':''}</tr></thead><tbody>${ds.map(d=>`<tr><td><b>${d.member_name||'-'}</b><small>ID ${d.rp_id||'-'}</small></td><td>${new Date(d.created_at).toLocaleString('pt-BR')}</td><td>${d.leaves}</td><td>${d.kits}</td><td>${money(d.gross_amount)}</td><td>${money(d.member_amount)}</td><td><span class="status ${d.payment_status}">${d.payment_status}</span></td>${actions?`<td>${d.payment_status==='pendente'?`<button class="pay-btn" onclick="pay('${d.id}')">PAGAR</button>`:'<span class="paid-mark">✓ PAGO</span>'}</td>`:''}</tr>`).join('')||'<tr><td colspan="8">Nenhum registro.</td></tr>'}</tbody></table></div>`;}
async function payments(){header('Pagamentos','Central financeira da liderança');const ds=await deliveries(),pending=ds.filter(d=>d.payment_status==='pendente'),sum=pending.reduce((s,d)=>s+Number(d.member_amount),0);C.innerHTML=`<div class="payment-head"><div><span>TOTAL PENDENTE</span><strong>${money(sum)}</strong><small>${pending.length} pagamentos aguardando</small></div>${pending.length?'<button onclick="payAll()">PAGAR TODOS</button>':''}</div><div class="payment-rules"><span>Meta <b>${B13_RULES.dailyGoal.toLocaleString('pt-BR')} folhas</b></span><span>Membro <b>${Math.round(B13_RULES.memberPercent*100)}%</b></span><span>FAC <b>${Math.round(B13_RULES.orgPercent*100)}%</b></span><span>Venda membro <b>${money(B13_RULES.memberSalePrice)}</b></span><span>Venda público <b>${money(B13_RULES.publicPrice)}</b></span></div><div class="admin-block"><div class="admin-block-head"><h3>Fila de pagamento</h3><span>Valores pendentes seguem a configuração atual</span></div>${deliveryTable(ds,true)}</div>`;}
window.pay=async id=>{if(!confirm('Confirmar este pagamento?'))return;try{await b13Rpc('b13_admin_pay',{p_token:b13Token(),p_delivery_id:id});showToast('Pagamento confirmado.');payments();}catch(e){showToast((e.message||e).replace('B13: ',''),'error')}};
window.payAll=async()=>{if(!confirm('Confirmar TODOS os pagamentos pendentes?'))return;try{await b13Rpc('b13_admin_pay_all',{p_token:b13Token()});showToast('Pagamentos processados.');payments();}catch(e){showToast((e.message||e).replace('B13: ',''),'error')}};
async function goals(){header('Metas','Acompanhe o progresso de cada membro hoje');const data=await b13Rpc('b13_admin_daily_progress',{p_token:b13Token()});C.innerHTML=`<div class="goal-admin-grid">${(data||[]).map(r=>{const pct=Math.min(100,Math.round(Number(r.total_leaves)/B13_RULES.dailyGoal*100));return `<article><div><b>${r.member_name}</b><span>${r.total_leaves}/${B13_RULES.dailyGoal}</span></div><div class="admin-progress"><i style="width:${pct}%"></i></div><footer><span>${pct}%</span><em class="${pct>=100?'done':pct>=50?'mid':'low'}">${pct>=100?'CONCLUÍDA':pct>=50?'EM ANDAMENTO':'PROGRESSO BAIXO'}</em></footer></article>`}).join('')}</div>`;}
async function ranking(){header('Ranking','Desempenho geral');const data=await b13Rpc('b13_admin_ranking',{p_token:b13Token()});C.innerHTML=`<div class="admin-block"><div class="admin-block-head"><h3>Top Farm</h3></div><div class="admin-ranking">${(data||[]).map((r,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span><strong>${r.member_name}</strong><small>${r.total_deliveries} entregas</small></span><em>${Number(r.total_leaves).toLocaleString('pt-BR')} folhas</em></div>`).join('')}</div></div>`;}
async function notices(){header('Avisos','Publique comunicados para os membros');const data=await b13Rpc('b13_list_notices',{p_token:b13Token()});C.innerHTML=`<div class="leader-grid"><section class="admin-block"><div class="admin-block-head"><h3>Novo aviso</h3></div><div class="admin-form"><label>Título<input id="noticeTitle"></label><label>Mensagem<textarea id="noticeBody" rows="5"></textarea></label><label class="check"><input id="noticeImportant" type="checkbox"> Marcar como importante</label><button onclick="publishNotice()">PUBLICAR AVISO</button></div></section><section class="admin-block"><div class="admin-block-head"><h3>Publicados</h3></div><div class="notice-admin-list">${(data||[]).map(n=>`<article><b>${n.title}</b><p>${n.body}</p><small>${new Date(n.created_at).toLocaleString('pt-BR')}</small></article>`).join('')||'<p class="muted">Nenhum aviso.</p>'}</div></section></div>`;}
window.publishNotice=async()=>{const title=noticeTitle.value.trim(),body=noticeBody.value.trim();if(!title||!body)return showToast('Preencha título e mensagem.','error');try{await b13Rpc('b13_admin_publish_notice',{p_token:b13Token(),p_title:title,p_body:body,p_important:noticeImportant.checked});showToast('Aviso publicado.');notices();}catch(e){showToast((e.message||e).replace('B13: ',''),'error')}};
async function logs(){header('Logs Administrativos','Histórico das ações da liderança');const data=await b13Rpc('b13_admin_logs',{p_token:b13Token()});C.innerHTML=`<div class="admin-block"><div class="admin-block-head"><h3>Últimas ações</h3></div><div class="log-list">${(data||[]).map(l=>`<div><time>${new Date(l.created_at).toLocaleString('pt-BR')}</time><b>${l.action}</b><small>${l.actor_name||'Sistema'}</small></div>`).join('')||'<p class="muted">Nenhum log.</p>'}</div></div>`;}
async function settings(){
  header('Configurações','Edite as regras financeiras e a meta diária');
  await b13LoadSettings();
  const r=calcDelivery(B13_RULES.dailyGoal);
  C.innerHTML=`<div class="settings-layout">
    <section class="admin-block settings-editor"><div class="admin-block-head"><h3>REGRAS EDITÁVEIS</h3><span>Salvas no Supabase</span></div>
      <div class="settings-form">
        <label>Meta diária (folhas)<input id="cfgDailyGoal" type="number" min="1" step="1" value="${B13_RULES.dailyGoal}"></label>
        <label>Venda para membro ($ por kit)<input id="cfgMemberSale" type="number" min="0" step="0.01" value="${B13_RULES.memberSalePrice}"></label>
        <label>Venda para público ($ por kit)<input id="cfgPublicPrice" type="number" min="0" step="0.01" value="${B13_RULES.publicPrice}"></label>
        <label>Porcentagem do membro (%)<input id="cfgMemberPercent" type="number" min="0" max="100" step="0.01" value="${(B13_RULES.memberPercent*100).toFixed(2)}"></label>
        <label>Porcentagem FAC B13 (%)<input id="cfgOrgPercent" type="number" min="0" max="100" step="0.01" value="${(B13_RULES.orgPercent*100).toFixed(2)}"></label>
        <label>Conversão<input value="1 folha = ${B13_RULES.kitsPerLeaf} kits" disabled></label>
      </div>
      <div class="settings-actions"><button class="settings-save" id="saveSettingsBtn">SALVAR CONFIGURAÇÕES</button><small>Ao salvar, novas entregas usam as novas regras e pagamentos pendentes são recalculados automaticamente. Pagamentos já marcados como pagos não são alterados.</small></div>
    </section>
    <section class="admin-block settings-preview"><div class="admin-block-head"><h3>RESUMO DA META</h3><span id="settingsPreviewBadge">ATUAL</span></div><div id="settingsPreview"></div></section>
  </div>`;
  const dg=document.getElementById('cfgDailyGoal'),ms=document.getElementById('cfgMemberSale'),pp=document.getElementById('cfgPublicPrice'),mp=document.getElementById('cfgMemberPercent'),op=document.getElementById('cfgOrgPercent');
  const preview=()=>{const goal=Math.max(1,Number(dg.value||0)),memberPct=Math.max(0,Number(mp.value||0))/100,orgPct=Math.max(0,Number(op.value||0))/100,kits=goal*B13_RULES.kitsPerLeaf,gross=kits*Math.max(0,Number(pp.value||0));document.getElementById('settingsPreview').innerHTML=`<div class="settings-board"><div><span>META DIÁRIA</span><b>${goal.toLocaleString('pt-BR')} folhas</b></div><div><span>KITS NA META</span><b>${kits.toLocaleString('pt-BR')} kits</b></div><div><span>VENDA MEMBRO</span><b>${money(ms.value)}</b></div><div><span>VENDA PÚBLICO</span><b>${money(pp.value)}</b></div><div><span>MEMBRO</span><b>${(memberPct*100).toFixed(2).replace('.00','')}% • ${money(gross*memberPct)}</b></div><div><span>FAC B13</span><b>${(orgPct*100).toFixed(2).replace('.00','')}% • ${money(gross*orgPct)}</b></div></div><div class="settings-total"><span>Total estimado na meta</span><strong>${money(gross)}</strong></div>`;};
  [dg,ms,pp,mp,op].forEach(el=>el.addEventListener('input',preview));
  mp.addEventListener('input',()=>{const v=Math.max(0,Math.min(100,Number(mp.value||0)));op.value=(100-v).toFixed(2);preview();});
  op.addEventListener('input',()=>{const v=Math.max(0,Math.min(100,Number(op.value||0)));mp.value=(100-v).toFixed(2);preview();});
  preview();
  document.getElementById('saveSettingsBtn').onclick=async()=>{const btn=document.getElementById('saveSettingsBtn'),memberPct=Number(mp.value),orgPct=Number(op.value);if(Math.abs((memberPct+orgPct)-100)>0.01)return showToast('As porcentagens precisam somar 100%.','error');btn.disabled=true;btn.textContent='SALVANDO...';try{const data=await b13Rpc('b13_admin_update_settings',{p_token:b13Token(),p_daily_goal:Number(dg.value),p_member_percent:memberPct/100,p_org_percent:orgPct/100,p_member_sale_price:Number(ms.value),p_public_price:Number(pp.value)});b13ApplySettings(data);showToast('Configurações atualizadas. Pagamentos pendentes recalculados.');await settings();}catch(e){showToast((e.message||e).replace('B13: ',''),'error');btn.disabled=false;btn.textContent='SALVAR CONFIGURAÇÕES';}};
}
