let ctx=null,currentPage='dashboard';const C=document.getElementById('leaderContent');document.getElementById('logoutBtn').onclick=signOutB13;document.querySelectorAll('#leaderNav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
(async()=>{ctx=await getSessionProfile();if(!ctx)return;if(!['gerente','sub_lider','lider'].includes(ctx.profile.role)){location.href='member.html';return;}userName.textContent=ctx.profile.name;userRole.textContent=ctx.profile.role.replace('_',' ').toUpperCase();go('dashboard');})();
function go(p){currentPage=p;document.querySelectorAll('#leaderNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render();}
function header(t,s){pageTitle.textContent=t;pageSubtitle.textContent=s||'';}
async function profiles(filter=''){let q=b13.from('profiles').select('*').order('created_at',{ascending:false});if(filter)q=q.eq('approved',filter==='approved');const {data,error}=await q;if(error)throw error;return data||[];}
async function deliveries(){const {data,error}=await b13.from('deliveries').select('*, profiles!deliveries_member_id_fkey(name,rp_id)').order('created_at',{ascending:false});if(error)throw error;return data||[];}
async function render(){C.innerHTML='<div class="loading">Carregando administração...</div>';try{if(currentPage==='dashboard')await dashboard();if(currentPage==='members')await members();if(currentPage==='approvals')await approvals();if(currentPage==='deliveries')await allDeliveries();if(currentPage==='payments')await payments();if(currentPage==='goals')await goals();if(currentPage==='ranking')await ranking();if(currentPage==='notices')await notices();if(currentPage==='logs')await logs();if(currentPage==='settings')settings();}catch(e){C.innerHTML=`<div class="error-card">${e.message}</div>`}}
async function dashboard(){header('Dashboard','Visão geral da organização');const ps=await profiles(),ds=await deliveries(),active=ps.filter(p=>p.approved&&p.status==='ativo').length,pendingMembers=ps.filter(p=>!p.approved).length,pending=ds.filter(d=>d.payment_status==='pendente').reduce((s,d)=>s+Number(d.member_amount),0),leaves=ds.reduce((s,d)=>s+d.leaves,0);C.innerHTML=`<div class="admin-metrics"><div><span>MEMBROS ATIVOS</span><strong>${active}</strong><small>${pendingMembers} aguardando aprovação</small></div><div><span>PAGAMENTOS PENDENTES</span><strong>${money(pending)}</strong><small>valor para membros</small></div><div><span>FOLHAS REGISTRADAS</span><strong>${leaves.toLocaleString('pt-BR')}</strong><small>${(leaves*3).toLocaleString('pt-BR')} kits</small></div><div><span>ENTREGAS</span><strong>${ds.length}</strong><small>registros totais</small></div></div><div class="leader-grid"><section class="admin-block"><div class="admin-block-head"><h3>Pagamentos aguardando</h3><button onclick="go('payments')">ABRIR CENTRAL</button></div>${paymentMini(ds.filter(d=>d.payment_status==='pendente').slice(0,6))}</section><section class="admin-block"><div class="admin-block-head"><h3>Novos cadastros</h3><button onclick="go('approvals')">VER TODOS</button></div><div class="admin-list">${ps.filter(p=>!p.approved).slice(0,6).map(p=>`<div><span><b>${p.name}</b><small>ID ${p.rp_id}</small></span><em>PENDENTE</em></div>`).join('')||'<p class="muted">Nenhum cadastro pendente.</p>'}</div></section></div>`;}
function paymentMini(ds){return `<div class="admin-list">${ds.map(d=>`<div><span><b>${d.profiles?.name||'Membro'}</b><small>${d.leaves} folhas • ${new Date(d.created_at).toLocaleDateString('pt-BR')}</small></span><strong>${money(d.member_amount)}</strong></div>`).join('')||'<p class="muted">Nenhum pagamento pendente.</p>'}</div>`;}
async function members(){header('Membros','Gerencie cargos e acessos');const ps=(await profiles()).filter(p=>p.approved);C.innerHTML=`<div class="admin-block"><div class="admin-block-head"><h3>Membros cadastrados</h3><span>${ps.length} registros</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Nome</th><th>ID</th><th>Discord</th><th>Cargo</th><th>Status</th><th>Ações</th></tr></thead><tbody>${ps.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.rp_id}</td><td>${p.discord||'-'}</td><td><select onchange="changeRole('${p.id}',this.value)">${['membro','recrutador','gerente','sub_lider','lider'].map(r=>`<option value="${r}" ${p.role===r?'selected':''}>${r.replace('_',' ')}</option>`).join('')}</select></td><td><span class="status ${p.status==='ativo'?'pago':'pendente'}">${p.status}</span></td><td><button class="small-action" onclick="toggleStatus('${p.id}','${p.status}')">${p.status==='ativo'?'Desativar':'Ativar'}</button></td></tr>`).join('')}</tbody></table></div></div>`;}
window.changeRole=async(id,role)=>{const {error}=await b13.from('profiles').update({role}).eq('id',id);if(error)return showToast(error.message,'error');await logAction(`Cargo alterado para ${role}`,id);showToast('Cargo atualizado.');};
window.toggleStatus=async(id,status)=>{const next=status==='ativo'?'inativo':'ativo';const {error}=await b13.from('profiles').update({status:next}).eq('id',id);if(error)return showToast(error.message,'error');await logAction(`Status alterado para ${next}`,id);showToast('Status atualizado.');members();};
async function approvals(){header('Aprovações','Novos membros aguardando acesso');const ps=(await profiles()).filter(p=>!p.approved);C.innerHTML=`<div class="approval-grid">${ps.map(p=>`<article class="approval-card"><div class="approval-id">ID ${p.rp_id}</div><h3>${p.name}</h3><p>${p.discord||'Sem Discord informado'}</p><small>${new Date(p.created_at).toLocaleString('pt-BR')}</small><div><button class="approve" onclick="approveMember('${p.id}')">APROVAR</button><button class="reject" onclick="rejectMember('${p.id}')">RECUSAR</button></div></article>`).join('')||'<div class="empty-admin">Nenhum cadastro aguardando aprovação.</div>'}</div>`;}
window.approveMember=async id=>{const {error}=await b13.from('profiles').update({approved:true,status:'ativo'}).eq('id',id);if(error)return showToast(error.message,'error');await logAction('Cadastro aprovado',id);showToast('Membro aprovado.');approvals();};
window.rejectMember=async id=>{const {error}=await b13.from('profiles').update({status:'inativo'}).eq('id',id);if(error)return showToast(error.message,'error');await logAction('Cadastro recusado/desativado',id);showToast('Cadastro recusado.');approvals();};
async function allDeliveries(){header('Entregas','Todas as entregas registradas');const ds=await deliveries();C.innerHTML=`<div class="admin-block"><div class="admin-block-head"><h3>Histórico geral</h3><span>${ds.length} entregas</span></div>${deliveryTable(ds)}</div>`;}
function deliveryTable(ds,actions=false){return `<div class="table-wrap"><table class="admin-table"><thead><tr><th>Membro</th><th>Data</th><th>Folhas</th><th>Kits</th><th>Total</th><th>20%</th><th>Status</th>${actions?'<th>Ação</th>':''}</tr></thead><tbody>${ds.map(d=>`<tr><td><b>${d.profiles?.name||'-'}</b><small>ID ${d.profiles?.rp_id||'-'}</small></td><td>${new Date(d.created_at).toLocaleString('pt-BR')}</td><td>${d.leaves}</td><td>${d.kits}</td><td>${money(d.gross_amount)}</td><td>${money(d.member_amount)}</td><td><span class="status ${d.payment_status}">${d.payment_status}</span></td>${actions?`<td>${d.payment_status==='pendente'?`<button class="pay-btn" onclick="pay('${d.id}')">PAGAR</button>`:'<span class="paid-mark">✓ PAGO</span>'}</td>`:''}</tr>`).join('')||'<tr><td colspan="8">Nenhum registro.</td></tr>'}</tbody></table></div>`;}
async function payments(){header('Pagamentos','Central financeira da liderança');const ds=await deliveries(),pending=ds.filter(d=>d.payment_status==='pendente'),sum=pending.reduce((s,d)=>s+Number(d.member_amount),0);C.innerHTML=`<div class="payment-head"><div><span>TOTAL PENDENTE</span><strong>${money(sum)}</strong><small>${pending.length} pagamentos aguardando</small></div>${pending.length?'<button onclick="payAll()">PAGAR TODOS</button>':''}</div><div class="admin-block"><div class="admin-block-head"><h3>Fila de pagamento</h3></div>${deliveryTable(ds,true)}</div>`;}
window.pay=async id=>{if(!confirm('Confirmar este pagamento?'))return;const {error}=await b13.from('deliveries').update({payment_status:'pago',paid_at:new Date().toISOString(),paid_by:ctx.profile.id}).eq('id',id);if(error)return showToast(error.message,'error');await logAction('Pagamento confirmado',null,id);showToast('Pagamento confirmado.');payments();};
window.payAll=async()=>{if(!confirm('Confirmar TODOS os pagamentos pendentes?'))return;const {data:ids}=await b13.from('deliveries').select('id').eq('payment_status','pendente');for(const d of ids||[])await b13.from('deliveries').update({payment_status:'pago',paid_at:new Date().toISOString(),paid_by:ctx.profile.id}).eq('id',d.id);await logAction('Pagamentos pendentes confirmados em lote');showToast('Pagamentos processados.');payments();};
async function goals(){header('Metas','Acompanhe o progresso de cada membro hoje');const {data,error}=await b13.rpc('get_b13_daily_progress');if(error)throw error;C.innerHTML=`<div class="goal-admin-grid">${(data||[]).map(r=>{const pct=Math.min(100,Math.round(r.total_leaves/B13_RULES.dailyGoal*100));return `<article><div><b>${r.member_name}</b><span>${r.total_leaves}/${B13_RULES.dailyGoal}</span></div><div class="admin-progress"><i style="width:${pct}%"></i></div><footer><span>${pct}%</span><em class="${pct>=100?'done':pct>=50?'mid':'low'}">${pct>=100?'CONCLUÍDA':pct>=50?'EM ANDAMENTO':'PROGRESSO BAIXO'}</em></footer></article>`}).join('')}</div>`;}
async function ranking(){header('Ranking','Desempenho geral');const {data,error}=await b13.rpc('get_b13_ranking');if(error)throw error;C.innerHTML=`<div class="admin-block"><div class="admin-block-head"><h3>Top Farm</h3></div><div class="admin-ranking">${(data||[]).map((r,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span><strong>${r.member_name}</strong><small>${r.total_deliveries} entregas</small></span><em>${r.total_leaves.toLocaleString('pt-BR')} folhas</em></div>`).join('')}</div></div>`;}
async function notices(){header('Avisos','Publique comunicados para os membros');const {data,error}=await b13.from('notices').select('*').order('created_at',{ascending:false});if(error)throw error;C.innerHTML=`<div class="leader-grid"><section class="admin-block"><div class="admin-block-head"><h3>Novo aviso</h3></div><div class="admin-form"><label>Título<input id="noticeTitle"></label><label>Mensagem<textarea id="noticeBody" rows="5"></textarea></label><label class="check"><input id="noticeImportant" type="checkbox"> Marcar como importante</label><button onclick="publishNotice()">PUBLICAR AVISO</button></div></section><section class="admin-block"><div class="admin-block-head"><h3>Publicados</h3></div><div class="notice-admin-list">${(data||[]).map(n=>`<article><b>${n.title}</b><p>${n.body}</p><small>${new Date(n.created_at).toLocaleString('pt-BR')}</small></article>`).join('')||'<p class="muted">Nenhum aviso.</p>'}</div></section></div>`;}
window.publishNotice=async()=>{const title=noticeTitle.value.trim(),body=noticeBody.value.trim();if(!title||!body)return showToast('Preencha título e mensagem.','error');const {error}=await b13.from('notices').insert({title,body,important:noticeImportant.checked,created_by:ctx.profile.id});if(error)return showToast(error.message,'error');await logAction(`Aviso publicado: ${title}`);showToast('Aviso publicado.');notices();};
async function logs(){header('Logs Administrativos','Histórico das ações da liderança');const {data,error}=await b13.from('admin_logs').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;C.innerHTML=`<div class="admin-block"><div class="admin-block-head"><h3>Últimas ações</h3></div><div class="log-list">${(data||[]).map(l=>`<div><time>${new Date(l.created_at).toLocaleString('pt-BR')}</time><b>${l.action}</b><small>${l.actor_name||'Sistema'}</small></div>`).join('')||'<p class="muted">Nenhum log.</p>'}</div></div>`;}
function settings(){header('Configurações','Regras atuais do sistema');const r=calcDelivery(B13_RULES.dailyGoal);C.innerHTML=`<div class="settings-board"><div><span>META DIÁRIA</span><b>${B13_RULES.dailyGoal} folhas</b></div><div><span>CONVERSÃO</span><b>1 folha = ${B13_RULES.kitsPerLeaf} kits</b></div><div><span>VENDA MEMBRO</span><b>${money(B13_RULES.memberSalePrice)}</b></div><div><span>VENDA PÚBLICO</span><b>${money(B13_RULES.publicPrice)}</b></div><div><span>MEMBRO</span><b>20% • ${money(r.member_amount)}</b></div><div><span>FAC B13</span><b>80% • ${money(r.org_amount)}</b></div></div><div class="security-note"><b>SEGURANÇA</b><p>As permissões administrativas também são protegidas no Supabase por RLS. Esconder um botão não é a única proteção.</p></div>`;}
async function logAction(action,target_user_id=null,delivery_id=null){await b13.from('admin_logs').insert({action,actor_id:ctx.profile.id,actor_name:ctx.profile.name,target_user_id,delivery_id});}
