let ctx=null, currentPage='home';
const C=document.getElementById('memberContent');
document.getElementById('logoutBtn').onclick=signOutB13;
document.querySelectorAll('#memberNav button').forEach(b=>b.onclick=()=>go(b.dataset.page));

(async()=>{
  ctx=await getSessionProfile(); if(!ctx)return;
  if(['gerente','sub_lider','lider'].includes(ctx.profile.role)){location.href='leader.html';return;}
  if(!ctx.profile.approved || ctx.profile.status!=='ativo'){await signOutB13();return;}
  userName.textContent=ctx.profile.name;userRole.textContent='Membro';avatar.textContent=initials(ctx.profile.name);go('home');
})();

function go(page){currentPage=page;document.querySelectorAll('#memberNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));render();}
function title(t){pageTitle.textContent=t;}
async function myDeliveries(){const {data,error}=await b13.from('deliveries').select('*').eq('member_id',ctx.profile.id).order('created_at',{ascending:false});if(error)throw error;return data||[];}
function todayOnly(ds){const today=new Date().toLocaleDateString('pt-BR');return ds.filter(d=>new Date(d.created_at).toLocaleDateString('pt-BR')===today);}
function deliveryRows(ds){return ds.map(d=>`<tr><td>${new Date(d.created_at).toLocaleString('pt-BR')}</td><td>${d.leaves}</td><td>${d.kits}</td><td>${money(d.member_amount)}</td><td><span class="status ${d.payment_status}">${d.payment_status==='pago'?'PAGO':'PENDENTE'}</span></td></tr>`).join('')||'<tr><td colspan="5" class="muted">Nenhuma entrega registrada.</td></tr>';}
async function render(){C.innerHTML='<div class="loading">Carregando...</div>';try{if(currentPage==='home')await home();if(currentPage==='deliver')deliver();if(currentPage==='history')await history();if(currentPage==='goal')await goal();if(currentPage==='payments')await payments();if(currentPage==='ranking')await ranking();if(currentPage==='notices')await notices();}catch(e){C.innerHTML=`<div class="error-card">${e.message}</div>`}}
async function home(){title('Início');const all=await myDeliveries(),ds=todayOnly(all),leaves=ds.reduce((s,d)=>s+d.leaves,0),pending=ds.filter(d=>d.payment_status==='pendente').reduce((s,d)=>s+Number(d.member_amount),0),paid=ds.filter(d=>d.payment_status==='pago').reduce((s,d)=>s+Number(d.member_amount),0),pct=Math.min(100,Math.round(leaves/B13_RULES.dailyGoal*100));C.innerHTML=`
<div class="member-welcome"><div><span>Bem-vindo de volta</span><h2>${ctx.profile.name}</h2><p>Registre suas entregas e acompanhe sua meta.</p></div><button class="member-cta" onclick="go('deliver')">+ NOVA ENTREGA</button></div>
<div class="member-cards"><div><small>META DO DIA</small><strong>${B13_RULES.dailyGoal}</strong><span>folhas</span></div><div><small>ENTREGUE</small><strong>${leaves}</strong><span>folhas</span></div><div><small>A RECEBER</small><strong>${money(pending)}</strong><span>pendente</span></div><div><small>JÁ RECEBIDO</small><strong>${money(paid)}</strong><span>pago</span></div></div>
<div class="member-panel"><div class="panel-head"><h3>Minha meta</h3><b>${pct}%</b></div><div class="big-progress"><i style="width:${pct}%"></i></div><p>${leaves} de ${B13_RULES.dailyGoal} folhas.</p>${pct>=100?'<div class="goal-done">✓ META DIÁRIA CONCLUÍDA</div>':''}</div>
<div class="member-panel"><div class="panel-head"><h3>Últimas entregas</h3><button onclick="go('history')">Ver histórico</button></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Folhas</th><th>Kits</th><th>A receber</th><th>Status</th></tr></thead><tbody>${deliveryRows(ds.slice(0,5))}</tbody></table></div></div>`;}
function deliver(){title('Entregar Farm');const x=calcDelivery(250);C.innerHTML=`<div class="delivery-stage"><section><div class="step-tag">PASSO 01</div><h2>Informe sua entrega</h2><p>Digite a quantidade de folhas que está colocando no cofre.</p><label>Quantidade de folhas<input id="leavesInput" type="number" min="1" value="250"></label><div class="member-rule">1 folha = 3 kits • cálculo da meta: ${money(B13_RULES.publicPrice)} por kit</div></section><aside><div class="step-tag">RESUMO</div><h3>Cálculo automático</h3><div id="calcBox"></div><button class="member-cta full" id="saveDelivery">CONFIRMAR ENTREGA</button></aside></div>`;const inp=document.getElementById('leavesInput'),box=document.getElementById('calcBox');const update=()=>{const r=calcDelivery(Math.max(0,Number(inp.value)));box.innerHTML=`<div class="receipt-row"><span>Folhas</span><b>${r.leaves}</b></div><div class="receipt-row"><span>Kits</span><b>${r.kits}</b></div><div class="receipt-row"><span>Valor total</span><b>${money(r.gross)}</b></div><div class="receipt-row highlight"><span>Você recebe • 20%</span><b>${money(r.member_amount)}</b></div><div class="receipt-row"><span>FAC B13 • 80%</span><b>${money(r.org_amount)}</b></div>`};inp.oninput=update;update();saveDelivery.onclick=async()=>{const r=calcDelivery(Math.max(1,Number(inp.value)));saveDelivery.disabled=true;const {error}=await b13.from('deliveries').insert({member_id:ctx.profile.id,leaves:r.leaves,kits:r.kits,gross_amount:r.gross,member_amount:r.member_amount,org_amount:r.org_amount,payment_status:'pendente'});saveDelivery.disabled=false;if(error)return showToast(error.message,'error');showToast('Entrega registrada com sucesso.');go('history');};}
async function history(){title('Minhas Entregas');const ds=await myDeliveries();C.innerHTML=`<div class="member-panel"><div class="panel-head"><h3>Histórico completo</h3><button onclick="go('deliver')">+ Nova entrega</button></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Folhas</th><th>Kits</th><th>A receber</th><th>Status</th></tr></thead><tbody>${deliveryRows(ds)}</tbody></table></div></div>`;}
async function goal(){title('Minha Meta');const all=await myDeliveries(),ds=todayOnly(all),leaves=ds.reduce((s,d)=>s+d.leaves,0),pct=Math.min(100,Math.round(leaves/B13_RULES.dailyGoal*100)),r=calcDelivery(B13_RULES.dailyGoal);C.innerHTML=`<div class="goal-hero"><span>SEU PROGRESSO</span><strong>${pct}%</strong><div class="big-progress"><i style="width:${pct}%"></i></div><p>${leaves} / ${B13_RULES.dailyGoal} folhas</p></div><div class="member-cards triple"><div><small>1.000 FOLHAS</small><strong>3.000</strong><span>kits</span></div><div><small>MEMBRO • 20%</small><strong>${money(r.member_amount)}</strong><span>na meta completa</span></div><div><small>FAC B13 • 80%</small><strong>${money(r.org_amount)}</strong><span>na meta completa</span></div></div>`;}
async function payments(){title('Meus Pagamentos');const ds=await myDeliveries(),pending=ds.filter(d=>d.payment_status==='pendente'),paid=ds.filter(d=>d.payment_status==='pago');C.innerHTML=`<div class="member-cards two-cards"><div><small>PENDENTE</small><strong>${money(pending.reduce((s,d)=>s+Number(d.member_amount),0))}</strong><span>aguardando liderança</span></div><div><small>PAGO</small><strong>${money(paid.reduce((s,d)=>s+Number(d.member_amount),0))}</strong><span>confirmado</span></div></div><div class="member-panel"><div class="panel-head"><h3>Pagamentos</h3></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Folhas</th><th>Kits</th><th>Valor</th><th>Status</th></tr></thead><tbody>${deliveryRows(ds)}</tbody></table></div></div>`;}
async function ranking(){title('Ranking');const {data,error}=await b13.rpc('get_b13_ranking');if(error)throw error;C.innerHTML=`<div class="ranking-list">${(data||[]).map((r,i)=>`<div class="rank-row ${i<3?'podium':''}"><b>#${i+1}</b><div><strong>${r.member_name}</strong><span>${r.total_leaves} folhas</span></div><em>${Math.min(100,Math.round(r.total_leaves/B13_RULES.dailyGoal*100))}%</em></div>`).join('')||'<p class="muted">Sem dados ainda.</p>'}</div>`;}
async function notices(){title('Avisos');const {data,error}=await b13.from('notices').select('*').order('created_at',{ascending:false});if(error)throw error;C.innerHTML=`<div class="notice-stack">${(data||[]).map(n=>`<article class="member-notice ${n.important?'important':''}"><span>${n.important?'IMPORTANTE':'COMUNICADO'}</span><h3>${n.title}</h3><p>${n.body}</p><small>${new Date(n.created_at).toLocaleString('pt-BR')}</small></article>`).join('')||'<p class="muted">Nenhum aviso publicado.</p>'}</div>`;}
